### ISSUE TITLE
Downpayment minimum values throws incorrect warnings

### ISSUE THREAD

**Issue by ianhussey** [connorbenton/rentbuy#1]
Hi, 

Amazing tool, thank you very much! 

I notice that the app throws the warning message "Total Down payment must be at least 20 and not more than 100 percent" when Initial Costs->% Down from second pillar is less than 10%, even when the total amount down is still above 20%, i.e., when % Down from own funds + 3rd pillar is >20%. 

I think this bug is probably related to the const rules defined on line 15 of src/components/HelloWorld.vue , however I'm not that familiar with javascript so I haven't dug further than this.

bw
Ian

**Comment by connorbenton** [comment]
Should be fixed in the latest commits!
