### ISSUE TITLE
[feature request] Model the finite duration of mortgages

### ISSUE THREAD

**Issue by ianhussey** [connorbenton/rentbuy#2]
Again, great tool. As someone else pointed out on reddit, one of few things holding it back is that - as far as I understand - the calculations act as if mortgages will last forever. Would it be possible to add a feature where the duration of the mortgage is adjustable, and after this period the mortgage costs drop to zero? I think this would serve to convey that buying can still be a better choice on a very long time scale. 

Thanks again for your work here!

**Comment by connorbenton** [comment]
Added a functionality to the calculator in the latest commits to address this scenario - also wrote an analysis that you can check here: https://www.reddit.com/r/Switzerland/comments/1cyl1xv/is_it_better_to_die_with_a_mortgage_i_updated_my/
